= ITU Metanorma Templates

image:https://github.com/metanorma/mn-templates-itu/workflows/test/badge.svg["Test Status", link="https://github.com/metanorma/mn-templates-itu/actions/workflows/test.yml"]
image:https://github.com/metanorma/mn-templates-itu/workflows/pages/badge.svg["Pages Status", link="https://github.com/metanorma/mn-templates-itu/actions/workflows/pages.yml"]
image:https://github.com/metanorma/mn-templates-itu/workflows/docker/badge.svg["Build Status", link="https://github.com/metanorma/mn-templates-itu/actions/workflows/docker.yml"]

This GitHub repository contains templates for ITU documents.

Note that the Apache license applies only to the template.
Once a document has been created
the license must reflect the ITU document license.

This repository is used by the `metanorma new` command to create new documents.

== Templates included

These templates are provided in this template repository:

`recommendation`::
  (`doctype == 'recommendation'`)
`supplement`::
  (`doctype == 'supplement'`)
`implementers-guide`::
  (`doctype == 'implementers-guide'`)
`technical-paper`::
  (`doctype == 'technical-paper'`)
`technical-report`::
  (`doctype == 'technical-report'`)
`joint-itu-iso-iec`::
  (`doctype == 'joint-itu-iso-iec'`)
`contribution-generic`::
  (`doctype == 'contribution'`), with no target document

The following templates are processed as document collections, separating a framing document
from a target document that they are proposing or revising:

`contribution-revision`::
  (`doctype == 'contribution'`) + (`document == *`)
`contribution-new-work-item`::
  (`doctype == 'contribution'`) + (`document == *`); different form presented as Annex A for `document == 'recommendation'`,
and any other document types

They are compiled as

[source,console]
----
bundle exec metanorma site generate -c contribution.yml --agree-to-terms
----

These ``doctype``s aren't supported yet:

* `recommendation-amendment`
* `recommendation-corrigendum`
* `recommendation-errata`
* `recommendation-annex`
* `resolution`
* `focus-group`
