= ITU Metanorma Templates

image:https://github.com/metanorma/mn-templates-itu/workflows/test/badge.svg["Test Status", link="https://github.com/metanorma/mn-templates-itu/actions/workflows/test.yml"]
image:https://github.com/metanorma/mn-templates-itu/workflows/pages/badge.svg["Pages Status", link="https://github.com/metanorma/mn-templates-itu/actions/workflows/pages.yml"]
image:https://github.com/metanorma/mn-templates-itu/workflows/docker/badge.svg["Build Status", link="https://github.com/metanorma/mn-templates-itu/actions/workflows/docker.yml"]

This GitHub repository contains templates for ITU documents.

Note that the Apache license applies only to the template.
Once a document has been created
the license must reflect the ITU document license.

This repository is used by the `metanorma new` command to create new documents.

== Templates included

These templates are provided in this template repository:

`recommendation`::
  (`doctype == 'recommendation'`)
`supplement`::
  (`doctype == 'supplement'`)
`implementers-guide`::
  (`doctype == 'implementers-guide'`)
`technical-paper`::
  (`doctype == 'technical-paper'`)
`technical-report`::
  (`doctype == 'technical-report'`)
`joint-itu-iso-iec`::
  (`doctype == 'joint-itu-iso-iec'`)

These ``doctype``s aren't supported yet:

* `recommendation-amendment`
* `recommendation-corrigendum`
* `recommendation-errata`
* `recommendation-annex`
* `resolution`
* `focus-group`
