= ITU Metanorma Templates

image:https://github.com/metanorma/mn-templates-itu/workflows/defaults/badge.svg["Build Status", link="https://github.com/metanorma/mn-templates-itu/actions?workflow=defaults"]

This GitHub repository contains templates for ITU documents.

Note that the Apache license applies only to the template.
Once a document has been created
the license must reflect the ITU document license.

This repository is used by the `metanorma new` command to create new documents.

== Templates included

These templates are provided in this template repository:

`recommendation`::
  (`doctype == 'recommendation'`)
`technical-paper`::
  (`doctype == 'technical-paper'`)

`supplement`::
  (`doctype == 'supplement'`)

These ``doctype``s aren't supported yet:

* `recommendation-supplement`
* `recommendation-amendment`
* `recommendation-corrigendum`
* `recommendation-errata`
* `recommendation-annex`
* `resolution`
* `focus-group`
* `implementers-guide`
* `technical-report`
* `joint-itu-iso-iec`
